### ISSUE TITLE
1.20.4 Update

### ISSUE THREAD

**Issue by PeppoDevStudio** [Mikedeejay2/SimpleStackPlugin#101]
Hi, would there be a dev or stable version that supports 1.20.2?

**Comment by Mikedeejay2** [comment]
Hi, there is a development version for 1.20.2 available through [GitHub Actions](https://github.com/Mikedeejay2/SimpleStackPlugin/actions), it can be downloaded [here](https://github.com/Mikedeejay2/SimpleStackPlugin/suites/17340902560/artifacts/990846915).

**Comment by PeppoDevStudio** [comment]
Hey, can you update plugin to 1.20.4?

**Comment by PeppoDevStudio** [comment]
i have this problem: https://mclo.gs/zw3VXMZ

**Comment by Mikedeejay2** [comment]
I will work on updating to 1.20.4 today. The log you posted looks to be an issue with 1.20.4, I'll make sure that's fixed as well.

**Comment by Mikedeejay2** [comment]
You may have already seen, but SimpleStack development versions have been updated to 1.20.4. Make sure to download the latest version through [GitHub Actions](https://github.com/Mikedeejay2/SimpleStackPlugin/actions). 

I will close this issue for now. If you have any issues with the plugin please let me know through a comment or a new issue. Thanks!
