### ISSUE TITLE
Please update to 1.21.1

### ISSUE THREAD

**Issue by TheFaik** [Mikedeejay2/SimpleStackPlugin#106]
Please update plugin to 1.21.1

**Comment by Mikedeejay2** [comment]
Thanks for creating this issue! I have updated Simple Stack to 1.21.1, you can find the download [here](https://github.com/Mikedeejay2/SimpleStackPlugin/actions/runs/10341987844). Let me know if you are experiencing any issues with the update.

**Comment by TheFaik** [comment]
> Thanks for creating this issue! I have updated Simple Stack to 1.21.1, you can find the download [here](https://github.com/Mikedeejay2/SimpleStackPlugin/actions/runs/10341987844). Let me know if you are experiencing any issues with the update.

Thanks for the update!
