### ISSUE TITLE
1.21.3 console error

### ISSUE THREAD

**Issue by PeppoDevStudio** [Mikedeejay2/SimpleStackPlugin#108]
<html>
<body>

[10:32:46] [Server thread/ERROR]: Error occurred while enabling SimpleStack v2.0.0-DEV-SNAPSHOT (Is it up to date?)
--
1648 | java.lang.NoClassDefFoundError: org/fusesource/jansi/Ansi
1649 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.internal.mikedeejay2lib.util.logging.EnhancedPluginLogger.<init>(EnhancedPluginLogger.java:68) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1650 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.internal.mikedeejay2lib.EnhancedJavaPlugin.forceColorfulLogger(EnhancedJavaPlugin.java:61) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1651 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.internal.mikedeejay2lib.EnhancedJavaPlugin.onEnable(EnhancedJavaPlugin.java:78) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1652 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.internal.mikedeejay2lib.BukkitPlugin.onEnable(BukkitPlugin.java:29) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1653 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.SimpleStack.onEnable(SimpleStack.java:66) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1654 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1655 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1656 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1657 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1658 | at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1659 | at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1660 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1661 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1662 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1663 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1664 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1665 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
1666 | Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.Ansi
1667 | at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1668 | at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1669 | at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
1670 | ... 17 more
1671 | [10:32:46] [Server thread/INFO]: [SimpleStack] Disabling SimpleStack v2.0.0-DEV-SNAPSHOT
1672 | [10:32:46] [Server thread/ERROR]: Error occurred while disabling SimpleStack v2.0.0-DEV-SNAPSHOT
1673 | java.lang.NullPointerException: Cannot invoke "com.mikedeejay2.simplestack.internal.mikedeejay2lib.gui.manager.GUIManager.closeAllGuis()" because "this.guiManager" is null
1674 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.internal.mikedeejay2lib.BukkitPlugin.onDisable(BukkitPlugin.java:44) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1675 | at SimpleStack-2.0.0-DEV-SNAPSHOT.jar/com.mikedeejay2.simplestack.SimpleStack.onDisable(SimpleStack.java:143) ~[SimpleStack-2.0.0-DEV-SNAPSHOT.jar:?]
1676 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1677 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1678 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1679 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1680 | at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1681 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1682 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
1683 | at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1684 | at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1685 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:767) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1686 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:529) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1687 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1688 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1689 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:339) ~[paper-1.21.3.jar:1.21.3-39-fdef6d3]
1690 | at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

</body>
</html>

**Comment by Mikedeejay2** [comment]
Hey, thanks for the bug report! Looks like this occurred because of a Paper update, this issue should be fixed in the latest version of SimpleStack [here](https://github.com/Mikedeejay2/SimpleStackPlugin/actions/runs/11924878467)
