### ISSUE TITLE
Add 1.21.4 Support

### ISSUE THREAD

**Issue by alexmartz710** [Mikedeejay2/SimpleStackPlugin#110]
1.21.4 was released a bit ago and I just want to be able to update my server and keep this plugin active, I totally forgot how to update the maven repo or I would do it myself hehe

**Comment by alexmartz710** [comment]
I managed to update it and get it working on my own, it was super easy so i doubt you need me to put it anywhere

**Comment by alexmartz710** [comment]
[SimpleStack-2.0.0-DEV-SNAPSHOT.zip](https://github.com/user-attachments/files/18174536/SimpleStack-2.0.0-DEV-SNAPSHOT.zip)
Here is the updated and working version for anyone that needs it in the meantime while Mike gets to update it on his own, I don't want to commit changes in a PR as this is a minor update and my contribution wouldn't be that big

**Comment by Mikedeejay2** [comment]
Thanks for your work! I've pushed a commit to update to 1.21.4, let me know if you experience any issues with it

**Comment by alexmartz710** [comment]
Change to drop broke the plugin btw, "Furthermore, booleam dropItem(boolean) has been deprecated in favor of Item dropItems(EquipmentSlot.HAND) or Item dropItem(EquipmentSlot.HAND, 1)." from https://github.com/PaperMC/Paper/pull/11810
Not sure how to implement the new change myself, I know it's in the nms mappings but not sure what values to replace the `"drop": ["drop(LItemStack;ZZZ)LEntityItem;", "a(LItemStack;ZZ)LEntityItem;"]` with

**Comment by alexmartz710** [comment]
Should I open a new issue? Not sure if you get notified for these @Mikedeejay2

**Comment by Mikedeejay2** [comment]
Thanks for notifying me of this issue! I've pushed a commit that should fix new Paper versions
