### ISSUE TITLE
This plugin will break custom GUIs created by other plugins.

### ISSUE THREAD

**Issue by Mikedeejay2** [Mikedeejay2/SimpleStackPlugin#20]
To fix this the inventory type should be checked. If it's not a custom inventory, proceed. If it does, use vanilla stacking behavior.

**Comment by PotatoIQ** [comment]
I can confirm, I'm experiencing this bug with skript GUIs and all other plugin GUIs

**Comment by SirCraftypants** [comment]
Just want to make sure i've not set up the config correctly so here it is.

https://paste.helpch.at/icevuhojor.makefile
