### ISSUE TITLE
1.16 not compatiable

### ISSUE THREAD

**Issue by yueyinqiu** [Mikedeejay2/SimpleStackPlugin#21]
An error occurred when enable the plugin:
```plain
[Server thread/ERROR]: [SimpleStack] Plugin SimpleStack v1.1.4 has failed to register events for class com.mikedeejay2.simplestack.listeners.PrepareSmithingListener because org/bukkit/event/inventory/PrepareSmithingEvent does not exist.
```

**Comment by Mikedeejay2** [comment]
I've tried to reproduce this error on 1.16.1 and 1.16.2 spigot and paper and it doesn't seem to want to show for me. 
What server type are you running? 
Does this happen on a startup / reload of the server or does it happen randomly? 
Do you have any other plugins that might conflict with this plugin?

**Comment by yueyinqiu** [comment]
1.16.1, Spigot, without any other plugins.  
It always happens no matter it's just started or reloaded.

**Comment by yueyinqiu** [comment]
![image](https://user-images.githubusercontent.com/18749772/91649886-19b7bb00-eaab-11ea-9145-59e23c7271da.png)
![image](https://user-images.githubusercontent.com/18749772/91649884-10c6e980-eaab-11ea-8cfa-db9c22028ae6.png)

**Comment by yueyinqiu** [comment]
I shared my server here: http://www.mediafire.com/file/a4lxd5on5522xf1/spigot-1.16.1.zip/file

Just start 'run.bat' (Windows) and the error may replicated.

**Comment by Mikedeejay2** [comment]
Thanks for the information, I'm pretty sure I know what the problem is. The PrepareSmithingEvent was recently added to Spigot on 7/22/2020 (See https://hub.spigotmc.org/jira/browse/SPIGOT-5950). Your spigot-1.16.1.jar was last modified at 7/4/2020 which means that the PrepareSmithingEvent can not be found in the jar. Updating your spigot should fix this.

**Comment by yueyinqiu** [comment]
So that's how it is!

**Comment by yueyinqiu** [comment]
It now runs well.
