### ISSUE TITLE
Translations to Simplified Chinese

### ISSUE THREAD

**Issue by yueyinqiu** [Mikedeejay2/SimpleStackPlugin#26]
A *.json file couldn't be uploaded here so I changed its extension to '.txt'.
[zh_cn.txt](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5148450/zh_cn.txt)

You may describe it like this: 'zh_cn - 简体中文' .

**Comment by yueyinqiu** [comment]
And try crwd.in! It's free for open source projects.

**Comment by Mikedeejay2** [comment]
Great, thank you! I'll work on getting a crwd.in open as well.

**Comment by Mikedeejay2** [comment]
I tested out crwd.in and while it looks nice and performs well it seems like a lot of the features that it comes with are premium features. After comparing a few different websites, I went with OneSky. Link for it can be found [Here](https://osu0azw.oneskyapp.com/).
