### ISSUE TITLE
Will only stack the first two of an item and refuses to allow anymore to be stacked.

### ISSUE THREAD

**Issue by SirCraftypants** [Mikedeejay2/SimpleStackPlugin#27]
Hi, I have a problem I've installed the lastest version on Paper 1.15.2and added WATER_BUCKET to the whitelist,  but it will only stack 2 buckets on pickup despite it being set to 64 and i can't stack any water buckets at all in my inventory, in survival mode?

Then if i throw another two water buckets to the ground and pick them up it stacks to two again, then i go in the inventory and drag the two buckets on to the other two stacked buckets and it only stacks to 3, then if i drop the 4th bucket and pick it up it stacks to 4.

But if i throw 4 buckets down and pick those up it only stack 2 and the other two un-stacked.

Does the same with potions.

https://paste.helpch.at/ulotekuvut.sql

**Comment by SirCraftypants** [comment]
Just want to make sure i've set up the config correctly so here it is.

https://paste.helpch.at/icevuhojor.makefile

**Comment by Mikedeejay2** [comment]
Your config is fine, it's a silly mistake on my end. I should have added a check to make sure that the Minecraft version that the plugin was on was at least 1.16 before attempting to check for a Smithing table's GUI. I'm releasing a bug fix update right now that will fix this.

**Comment by SirCraftypants** [comment]
awesome, thanks, appreciate your time and work, good job on the plugin.

**Comment by SirCraftypants** [comment]
Hi again, I can now self stack unstackable items now so that's cool but still have the 2 item stack issue.

Heres what i did to test it. 

I filled my entire inventory slots up with blocks, left 1 slot empty in my actionbar, dropped 5 buckets. went to pick the 5 buckets up but i only picked 2 up in a stack, the other 3 disappeared.
