### ISSUE TITLE
Villager trades not working with vanilla non-stacking items.

### ISSUE THREAD

**Issue by Schmidtdan** [Mikedeejay2/SimpleStackPlugin#29]
Villager trades aren't working quite right since installing SimpleStack.

If I trade a villager for a vanilla non-stacking item, like an Enchanted Book of Mending, the villager will give me the item, but not take the Emeralds - breaking world economy.  I tested this with Suspicious Stew as well and it's the same effect where Villager does not take payment. 

Vanilla stacking items. like paper or leather, seem to exchange just fine where the villager takes the Emeralds during trade. 

Running PaperMC-204 on Minecraft 1.16.3. Survival mode.

**Comment by Mikedeejay2** [comment]
Thank you for the bug report! The latest release should have fixed this bug. If you're still having issues with villager trading please add another comment explaining the issue and I will look into it.
