### ISSUE TITLE
Buckets disappear when crafting cake

### ISSUE THREAD

**Issue by ahegaoallday** [Mikedeejay2/SimpleStackPlugin#30]
I was crafting cakes and noticed afterwards, I got the cake but the the buckets of milk did not go back into my inventory as regular buckets. I tried a couple ways to see if the method I was using was wrong and all 3 ways I tried did not yield my buckets back. The first way I did it was simply clicking on the cake icon that puts all the ingredients in for 1 cake, and taking the cake back. Buckets gone. Next, I tried placing the buckets in along with the ingredients by hand. Still got cake, but again no buckets. Lastly, I tried doing both of those with multiple buckets to see if it needed to be full stacks in order to give my buckets back, and again I got cake and still no buckets returned.

**Comment by Mikedeejay2** [comment]
Thank you for the bug report! The latest update that I've just released should fix this issue. If you're still having issues, feel free to comment below and I'll make sure to take a look at them.
