### ISSUE TITLE
stackable when dropped

### ISSUE THREAD

**Issue by SirCraftypants** [Mikedeejay2/SimpleStackPlugin#34]
This plugin is awesome for being able to stack un-stackables within player inventories, my only issue is that it doesnt stack items upon them dropping to the ground. Plugins like Rosestackers does this but it doesn't stack un-stackables in Inventories like Simplestack. I'm not a fan of using two stacking plugins or two plugins that should do exactly what their title suggests they do.

Right now I've reverted to using Simplestack because it in my opnion offers something Rosestackers doesn't stacking un-stackables in inventories. The Dev of Rosestackers says shes taken my request of un-stackables being able to stack in inventories onboard and its on her list but far from a priority as it's not important to her which i found a little annoying considering i think stacking options is far more in keeping with a stacking plugin than spawners.

I'm hoping you would be kind enough to add the ability for Simplestacks to stack items when they drop to the ground within a radius of each other so i don't have to revert back to Rosestackers. It would without any doubt make Simplestack the best stack plugin out there doing what a stack plugin should. Thanks.

**Comment by Mikedeejay2** [comment]
That sounds like a great idea! I know of a way to implement this feature so when I have some free time I'll add it to the plugin.
