### ISSUE TITLE
Bug with the chests

### ISSUE THREAD

**Issue by MrFreasy** [Mikedeejay2/SimpleStackPlugin#42]
When a chest is broken and there are items such as swords and armor inside, they are dropped onto the ground stacked. 
The config is set up correctly to not stack them.

```
ListMode: Whitelist
Items:
- POTION
```

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! This was an issue where the item wasn't checked before it was stacked on the ground, causing the identified problem. Like last time I've attached an updated Simple Stack jar that you can use before the official update here:
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5478740/simplestack-1.3.0-SNAPSHOT.zip)
If you have any more problems I'd be happy to help!
