### ISSUE TITLE
Errors thrown to console when moving unstackables through a hopper

### ISSUE THREAD

**Issue by BenisonQPS** [Mikedeejay2/SimpleStackPlugin#43]
java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_16_R2.ItemStack.checkEmpty(ItemStack.java:156) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.ItemStack.setCount(ItemStack.java:976) ~[patched_1.16.3.jar:git-Paper-197]
	at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemStack.setAmount(CraftItemStack.java:149) ~[patched_1.16.3.jar:git-Paper-197]
	at com.mikedeejay2.simplestack.util.MoveUtils.moveItemToInventory(MoveUtils.java:97) ~[?:?]
	at com.mikedeejay2.simplestack.listeners.InventoryMoveItemListener$1.run(InventoryMoveItemListener.java:43) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-197]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-197]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-197]

**Comment by BenisonQPS** [comment]
This happens about every second, there are MANY more very similar to this

**Comment by Mikedeejay2** [comment]
Hello, thanks for the bug report! I can't seem to reproduce this issue. From the error you sent me, the plugin is attempting to move an empty item from one inventory to another inventory (Most likely through a hopper) and is causing the error.
What does your config for Simple Stack look like?
Try updating to this version of Simple Stack: 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5506586/simplestack-1.3.0-SNAPSHOT.zip)

**Comment by BenisonQPS** [comment]
Its the basic configuration, and yes its moving to a hopper. Thanks for the
snapshot file. I'll see if it fixes the issue. I kept looking for an update
but didn't see one. Lol

**Comment by BenisonQPS** [comment]
Okay. This is what I received from one of my server members today. Maybe this will help?
![Screenshot_20201109-165358_Discord](https://user-images.githubusercontent.com/73863008/98601803-8cb08f80-22ad-11eb-9511-17729eee3e87.jpg)

**Comment by BenisonQPS** [comment]
Not sure if you can change the title but it's actually not "chat"  but the Minecraft DOS console that gets all those messages

**Comment by BenisonQPS** [comment]
...and this Discord screenshot was after adding the recent simplestack that you sent me :(

**Comment by Mikedeejay2** [comment]
Here's a fix for shulker stacking, it was a bug where the code wasn't checking all properties of an item and it was only in the snapshot version: 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5513955/simplestack-1.3.0-SNAPSHOT.zip)
As for the errors being thrown to console I'm still trying to figure out how to reproduce it on my end so hopefully I'll have a fix for it soon.

**Comment by Mikedeejay2** [comment]
As a temporary fix I've added the ability to disable the stacking of unstackables through hoppers in the configuration file: 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5513979/simplestack-1.3.0-SNAPSHOT.zip)
Also, what other plugins are you using? It seems unlikely from the error, but there's always a chance that a plugin is conflicting with simple stack and leading to this issue. I'd like a list of the plugins so I know that I'm testing with the same configuration that the server is running. Thanks!

**Comment by Mikedeejay2** [comment]
I figured out what's causing the error, it occurs when 3 or more hoppers are moving items into hopper minecarts like this:
![2020-11-09_19 22 39](https://user-images.githubusercontent.com/58639173/98611971-1e75c800-22c1-11eb-9439-9f2d3e4eba4b.png)
Going to start working on a fix now.

**Comment by Mikedeejay2** [comment]
I've found the fix for this! Download it before release here: 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5514274/simplestack-1.3.0-SNAPSHOT.zip)
If you're still experiencing issues you can either add a comment to this issue and I'll open it back up or create a new issue. Thanks!

**Comment by BenisonQPS** [comment]
Thanks, Mike, I'll give it a try👍

**Comment by BenisonQPS** [comment]
Here is a list of plugins
![Screenshot_20201109-214213_VNC Viewer](https://user-images.githubusercontent.com/73863008/98621105-8b468d80-22d4-11eb-9f84-7691208ccd40.jpg)

**Comment by BenisonQPS** [comment]
Just wanted to update you-The disappearing signs issue appears to be fixed-I have the hopper setting turned off so it doesn't stack inside. As far as I know (Fingers Crossed), all the issues have been fixed (other than maybe some duplication issues which I'm waiting to hear back from), and WARN in the console, but that may just be items moving through hoppers etc. Thanks for your quick responses and diligent efforts to correct the issues.

**Comment by Mikedeejay2** [comment]
Awesome, I'm glad to hear it. If you have any more issues or errors with Simple Stack feel free to open up a new issue. The official release for 1.3.0 should be coming out in the next few days so keep an eye out for that as well. Thanks!
