### ISSUE TITLE
[BUG] Potions

### ISSUE THREAD

**Issue by MrFreasy** [Mikedeejay2/SimpleStackPlugin#45]
You can stack potions with different effects.
For example, you can combine a potion of strength with one of invisibility.

**Comment by Mikedeejay2** [comment]
This is an issue with the item comparison algorithm that the last SimpleStack 1.3.0 snapshot I gave you had.
I've fixed it in this version: 
[simplestack-1.3.0-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5507301/simplestack-1.3.0-SNAPSHOT.zip)
