### ISSUE TITLE
Entities without inventories can still pickup items - That causes an error

### ISSUE THREAD

**Issue by BenisonQPS** [Mikedeejay2/SimpleStackPlugin#47]
NinjaOnTheSticksToday at 4:13 PM
simple stack isnt working right aswell
[4:14 PM]
sometimes itll only place one thing in a chest/ inventory

Sorry, Mike. we have a new issue

**Comment by Mikedeejay2** [comment]
Thanks for reporting, do you have any steps to reproduce this? Does this have to do with hopper movement or placing items in inventories with your cursor? If it has to do with hoppers not stacking items, check that the "Hopper Movement Checks" option in the config is enabled and not disabled because if it is disabled hoppers will not stack items.

**Comment by Mikedeejay2** [comment]
Also, if you have any errors in console could you post one of them here?

**Comment by BenisonQPS** [comment]
Still getting a ton of "Warn" messages in the console. Just leaving for
work but I can do that for you when I get home.

**Comment by BenisonQPS** [comment]
Mike, just got home-Do you have a Discord?

**Comment by BenisonQPS** [comment]
[2020-11-13-1.log.gz](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5539515/2020-11-13-1.log.gz)

**Comment by Mikedeejay2** [comment]
Yes I have a Discord, it's Mikedeejay2#3606

**Comment by BenisonQPS** [comment]
[2020-11-12-2.log.gz](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5539523/2020-11-12-2.log.gz)


This one a lot of SimpleStack errors at the end-You'll notice A bunch of other ones that repeat and come up in red in the console as well- I have NO idea what they are from

**Comment by BenisonQPS** [comment]
Odd, it can't find you. I'm BenisonQPS #8300

**Comment by Mikedeejay2** [comment]
It looks like a zombie is attempting to pick up an item from the ground but the zombie doesn't have an inventory and that confuses the plugin. I'll add a fix for that
