### ISSUE TITLE
Issue with Ground Stacking.

### ISSUE THREAD

**Issue by SirCraftypants** [Mikedeejay2/SimpleStackPlugin#53]
Buckets are stacking on the ground but the amount stacking isn't visible on them.

Potion are not stacking on the ground.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! I'm going to wait a day or so for any more bug reports to come in before releasing a bug fix update but if you want to use this fix before then you can download it here:
[simplestack-1.3.1-SNAPSHOT.zip](https://github.com/Mikedeejay2/SimpleStackPlugin/files/5580880/simplestack-1.3.1-SNAPSHOT.zip)
