### ISSUE TITLE
Consumption of Mushroom Stew and Beetroot Soup

### ISSUE THREAD

**Issue by BingoRufus** [Mikedeejay2/SimpleStackPlugin#55]
Both mushroom stew and beetroot soup can be stacked, however, upon consumption, the stack of stew will be replaced with one bowl, as opposed to a bowl added to the player inventory and a subtraction of the itemstack.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! This fix will be available in Simple Stack v1.3.2.
