### ISSUE TITLE
Shulker in Shulker

### ISSUE THREAD

**Issue by DefinitvLegit** [Mikedeejay2/SimpleStackPlugin#56]
Please Fix that you can put shulkers in shulkers, thats a huge problem because you can get chunk baned, you have unlimited storage and you can lag the server. Exept of this the Plugin works perfect!
[https://i.ibb.co/VQ6vvrr/Unbenannt.png](url)

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! This bug has been fixed and will be available in the 1.3.3 update.
