### ISSUE TITLE
Item Stack won't work in certain inventories.

### ISSUE THREAD

**Issue by Kenaestic** [Mikedeejay2/SimpleStackPlugin#59]
**Used Simple Stack version**
1.3.3

**Used Spigot version**
Paper version git-Paper-318 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Describe the bug**
When depositing unstackable items to other inventories (like [shulker backpacks](https://www.spigotmc.org/resources/shulker-backpacks-1-13-1-16.67466/) or [minepacks](https://www.spigotmc.org/resources/minepacks-backpack-plugin-mc-1-7-1-16.19286/)), dragging the item to the other inventory causes only the first item to deposit while I'm still holding the rest of the stack. To fix this I have to manually open my inventory again, re-stack the items and shift click to deposit them in other inventories. As this first occured in Minepacks I suspected it might be [ChestSort](https://github.com/JEFF-Media-GbR/Spigot-ChestSort)'s hook, but the problem still persists even with ChestSort disabled. 

I noticed that both Minepacks and Shulker Backpacks have the same GUI when opened from the inventory:
https://i.imgur.com/mQVpDVt.png
https://i.imgur.com/SL1cZGw.png

While placing the shulkerbox and opening it looks different. This inventory works normally:
https://i.imgur.com/GuQUZNy.png

Here is a video:
https://streamable.com/pzdbt6
I used this video for a another bug report for Chestsort (inventory sorting). That's why you see the items jumping around in my inventory. However at 0:40 you can see I try to deposit a bucket of milk in my backpack, but it only deposits the first item.

**To Reproduce**
Install Minepacks or Shulker Backpacks along with Simple Stack and open one of these pugin's inventories. I suggest Shulker Backpacks because it's easier to set up. You will notice it behaves strangely with Simple Stack.

**Expected behavior**
What should happen is that all existing stacks stay intact. And it should be able to make new stacks in those inventories as if it was the player's own.

**Additional context**
This is a bug report I made on ChestSort's github regarding this:
https://github.com/JEFF-Media-GbR/Spigot-ChestSort/issues/99

If this is another Plugin's fault, let me know and I will forward it to the developer there.

**Comment by Mikedeejay2** [comment]
Yes, these issues are all Simple Stack's fault.

The issue with Minepacks and Shulker Backpacks is that they are custom GUIs and Simple Stack makes sure that the GUI isn't a custom GUI before processing an item. This was originally implemented this way because players were able to grab items that they shouldn't have been able to out of a custom GUI. I'm pretty sure that this is fixable.

For ChestSort I'll have to work on adding compatibility on Simple Stack's end for this. There currently isn't a good way for ChestSort's developer to add compatibility with Simple Stack but it should be relatively easy for me to add compatibility on Simple Stack's end.

**Comment by Kenaestic** [comment]
Good to hear it's fixable. Are you planning on adding compatibility for Chestsort? If so, I'll close the bug report there. And honestly, I'm impressed how well your plugin works in all other regards and I'm really happy with it.

**Comment by Mikedeejay2** [comment]
Yes, I am planning on adding support for ChestSort. Currently, I've fixed the issue with Shulker Backpacks and Minepacks, that fix will be in version 1.3.4. I'm not quite sure how long it will take me to add support for ChestSort though so there's a chance that it will have to come in a later release.

**Comment by Kenaestic** [comment]
> 
> 
> Yes, I am planning on adding support for ChestSort. Currently, I've fixed the issue with Shulker Backpacks and Minepacks, that fix will be in version 1.3.4. I'm not quite sure how long it will take me to add support for ChestSort though so there's a chance that it will have to come in a later release.

The newest update introduced a new duplication bug. When splitting a stack and adding it to my inventory from minepacks it turns it in a new stack of the original size. When depositing an item that adds to the stack in minepacks it adds 1 extra of the item type.

**Comment by Mikedeejay2** [comment]
Just did some testing and fixed this bug, thanks for the report! The issue that was causing this was inconsistencies between regular GUIs and custom GUIs as I explained in issue #61.

**Comment by Mikedeejay2** [comment]
Issues with Shulker Backpacks and Minepacks have been solved. Full chest sort compatibility is still an issue, however I'm moving it to issue #65. Closing this issue for now.
