### ISSUE TITLE
[BUG] Backpack Item Dupe

### ISSUE THREAD

**Issue by SirCraftypants** [Mikedeejay2/SimpleStackPlugin#62]
I'm using a Backpack Plugin named EpicBackpacks and SimpleStack is Duping Items.

When you add and then remove an Item fast between inventory and backpack, the item multiplies.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! Please try the newest release of Simple Stack. I had gotten another recent report of dragging items around a custom GUI created one extra item per slot causing the multiplication behavior that you might be talking about here. 
[Download Link for Simple Stack v1.3.5](https://github.com/Mikedeejay2/SimpleStackPlugin/releases/download/1.3.5/SimpleStack-1.3.5.jar)

**Comment by Mikedeejay2** [comment]
I'm going to close this issue for now, as I'm assuming it's been fixed with the latest version. If this isn't so, please leave a comment and I'll reopen this issue. Thanks!
