### ISSUE TITLE
Stacked Potions Deleting Items in Shulker Boxes

### ISSUE THREAD

**Issue by MasonX3** [Mikedeejay2/SimpleStackPlugin#63]
This bug was reported to me by one of my players, it seems that when you place stacked potions inside of a Shulker Box, then break the Shulker Box, the potions become unstacked and delete items inside of it to make space. For instance, in the attached screenshots, there are four potions stacked together, 3 beetroot seeds, and 25 stone bricks.

When the Shulker Box is broken, and then placed again, the four potions are unstacked, and there are only 22 Stone Bricks in the Shulker Box. 
![2020-12-16_14 30 22](https://user-images.githubusercontent.com/9630249/102403926-9b751b00-3fac-11eb-89db-3e129a9b9274.png)
![2020-12-16_14 30 29](https://user-images.githubusercontent.com/9630249/102403933-9fa13880-3fac-11eb-8ed2-277e8706dfb5.png)

There are no visible errors in the console at all, only that the items simply get deleted to make room for the stacked potions to be unstacked.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! I've been able to fix this bug and a bug fix release will be out soon including this fix. 

If you want a technical explanation of the bug:
When breaking a shulker box, items in shulker boxes are automatically stacked back down to their maximum stack amounts for vanilla by default. A fix for Simple Stack had been implemented a while back that had fixed this issue. However, there was an issue with this fix where it was first checking to make sure that the shulker box was whitelisted in the config before it attempted to perform this fix. The issue with that is if shulker boxes aren't added in the config and whitelist mode is on that means that the fix will not be performed and items will unstack and overflow in the shulker box, resulting in the item loss that you noticed in the screenshots above.
