### ISSUE TITLE
[BUG] Duplications

### ISSUE THREAD

**Issue by MrFreasy** [Mikedeejay2/SimpleStackPlugin#70]
When you click on a potion in a menu (like ShopGuiPlus), it's dropped on the ground.
Which does not happen when SimpleStack is disabled.

config:
`
Language: en_us
Item Amounts:
  Example Item: 32
Default Max Amount: 64
- POTION
List Mode: Whitelist
Hopper Movement Checks: true
Ground Stacking Checks: true
Creative Item Dragging: false
`
Version: version: 1.3.6

https://user-images.githubusercontent.com/46691191/103573890-4b181b80-4ecf-11eb-89ea-238a56317de6.mp4

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! I've identified what was causing this bug and have implemented a fix that will be in release 1.4.0. If you're interested in trying out the fix before the release I'll be publishing a new snapshot build soon on the [releases page on Github](https://github.com/Mikedeejay2/SimpleStackPlugin/releases). If this issue persists on your end after updating feel free to comment on this issue and I'll look into it.
