### ISSUE TITLE
the tools issues

### ISSUE THREAD

**Issue by warrenharper1990** [Mikedeejay2/SimpleStackPlugin#77]
the tools is not steaking again. they work if i remove the plugin and reinstall it. can you fix the issues.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! In order for me to figure out what's wrong, I need some more information:
* What version of Simple Stack and Minecraft are you using?
* What settings have you changed in the config?
* If possible, how can the bug be reproduced?
* Are there any errors being thrown in the console?

**Comment by warrenharper1990** [comment]
i download the newest version.

i had too go back too your plugin and redownload it. then it worked once.
then i tried it again and it stop working. i tried reload and still nothing
happen. i am using 1.16.5 that what i am on on minecraft.

**Comment by Thatcooldevguy** [comment]
Okay, from what I read, you have no knowledge of the of the English language.  You need to tell us what you are really having an issue with. I personally can't tell if its speaking, or the plugin.  Things like "the tools is not steaking again. they work if i remove the plugin and reinstall it. can you fix the issues." Sound like you have no brain, and just a 12 year old behind a keyboard, trying to figure out how to setup a plugin

We devs, unlike you, have a life. So please sir, what seems to be the issue? Follow what mikedeejay2 said.

Good Riddance.

**Comment by warrenharper1990** [comment]
are you kidding me i am a 27 year old guy who has disability and the plugin
is not working. it does not tell me on the console at all,

plus the chat does not show me anything.

**Comment by Mikedeejay2** [comment]
I'm very sorry about what Thatcooldevguy said. It was very rude for him to say the things that he did. I had deleted his message 3 minutes after he sent it, but unfortunately, a notification was still sent. I have talked with Thatcooldevguy through DMs and told him that what he said was wrong and inconsiderate. I completely understand and am willing to help anyone with any issues that they have regarding my plugins. Again, I'm deeply sorry.

**Comment by Mikedeejay2** [comment]
Are you using other plugins on the server that might be affecting Simple Stack? Sometimes plugins can have compatibility issues that lead to the plugin not working correctly.
On top of that, can you confirm that on the startup of your Minecraft server that the message `[SimpleStack] Enabling SimpleStack 1.3.6` is visible? There's a chance that the server isn't loading the plugin for some reason, if you see that message on start up that means the plugin is being loaded.
Thanks!

**Comment by warrenharper1990** [comment]
do you know any plugins that may have a effect too it

**Comment by Mikedeejay2** [comment]
Unfortunately no, there's no list of plugins that I have that are currently incompatible. If you send me the list of plugins that you're using I'll be able to install those plugins on my server and test to see if you're having compatibility issues with any other plugins that you're using.

Could you send me a list of the plugins that you are using on your server?

**Comment by warrenharper1990** [comment]
Ok

**Comment by Mikedeejay2** [comment]
Sorry, I didn't receive anything in that last message. You might have tried to attach your plugins to the email you sent but Github doesn't support that. Could you send me a list of your plugins, in text form, like this:
- Simple Stack
- Another Plugin
- Another Plugin
- etc

Thanks!

**Comment by warrenharper1990** [comment]
AutoEnchanter
bedwars
Better-Enchantments
EnchantPlus
Essentials
EssentialsGeoIP
EssentialsXMPP
HomeGUI
HubThat
MineHome
SeePlayerInventory
SuperVanish

**Comment by Mikedeejay2** [comment]
Hello! Apologies for no message for such a long time. If you're still having issues with items not stacking could you confirm that this is an issue on the new version 1.3.7 of Simple Stack? I was unable to find any compatibility issues with the plugin list you sent. If version 1.3.7 does not fix your issue I would be able to help resolve the issue more quickly through Discord. My user on Discord is `Mikedeejay2#3606`, feel free to reach out if you still want this issue fixed. I'll close this issue on Github for now as I and others have been unable to reproduce this issue.
