### ISSUE TITLE
[CRITICAL] DUPE ISSUE

### ISSUE THREAD

**Issue by ZeoNight** [Mikedeejay2/SimpleStackPlugin#84]
Problem: Dupelication

What's supposed to happen: Item not supposed to dupelicate

What's happening: The item is duped by 1 and sometimes more.

How to rep: Get an unstackble item and open your inventory (2 is recommended) and just spam right click and left click and just drag your mouse.

**Comment by ZeoNight** [comment]
@Mikedeejay2 can this be fixed asap?

**Comment by Mikedeejay2** [comment]
I'm at school right now, I'll be able to look at this when I get home at around 3:30pm eastern time. Thanks for the bug report!
