### ISSUE TITLE
Overstacking past set limit

### ISSUE THREAD

**Issue by Beta-51** [Mikedeejay2/SimpleStackPlugin#86]
If you are to right click on an unstackable item, that you gave a custom limit to, for example, two, if you right click it with the same item, it will go past the limit you set.
![image](https://user-images.githubusercontent.com/65312404/140652445-2a7695ed-401f-4abf-9bd7-5ff3e605eff9.png)
The limit for this item is two, yet right clicking the same item onto this stack will turn it to three.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! This issue has been fixed in commit d7416d1 and will be included in Simple Stack 1.3.9.
