### ISSUE TITLE
[BUG] Messing with other plugins Gui's

### ISSUE THREAD

**Issue by 00Hrtz** [Mikedeejay2/SimpleStackPlugin#90]
I love this stacking plugin, the problem i have though is, it's causing problem with my other plugins Gui's 

Example: I use Pyrofishingpro and Simplestack is causing some but not all of the buttons in the Gui to be dragged around the menu and placed when clicking the button. 

This is what the dev of the fishing plugin has said.

I'd go talk to that dev because it seems it's messing with simple GUIs
and event handlers. It could be something as small as event priority being set incorrectly

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! Yes, this is an issue that has been fixed many times over but different plugins have different ways of creating their own GUIs which requires that more checks are added in Simple Stack to prevent this issue. I'll look into the case of PyroFishingPro but if you have any issues with other GUIs please let me know as well.

**Comment by 00Hrtz** [comment]
I don't have any issues with other gui's, only the reported one, hoping you can fix it as my server heavily relies on your plugin.
