### ISSUE TITLE
Add compatibility to wildstacker

### ISSUE THREAD

**Issue by IncludivicS** [Mikedeejay2/SimpleStackPlugin#91]
When i use this plugin with wildstacker the item stacked on ground will be pick up as one quantity

**Comment by Mikedeejay2** [comment]
Thanks for the bug report! I believe that this issue can be fixed in Simple Stack's config by changing "Ground Item Stacking" to be false so that both stackers don't attempt to stack ground items at the same time. If changing this option doesn't fix the issue, please let me know.
