### ISSUE TITLE
Unique item list limit issue.

### ISSUE THREAD

**Issue by Luka27Svedalia** [Mikedeejay2/SimpleStackPlugin#95]
There's a limit of 36 items thrown in the unique item lists to for example blacklisting stacked items.
Any way to add a page 2, 3 etcetra? I find stacking tools and armor to be quite pointless regarding how stacking 5 pickaxes and mining with them uses up the durability of all 5 pickaxes at the same time, you are using 1 for the cost of 5.
![image](https://user-images.githubusercontent.com/110982134/183896871-907bc0d1-627e-4b10-bb41-d2fef23719c5.png)
And I need more pages to fit all the items.

**Comment by Mikedeejay2** [comment]
Thanks for the bug report, seems like this is an issue that was introduced in version 1.3.7. I've fixed this for the next update.

**Comment by Mikedeejay2** [comment]
I forgot to mention that from my testing, stacked tools only visually look like their durability is going down for the entire stack. When a tool is broken, the stack is decreased by one and the tool is replenished to full durability. This might be different if you have plugins that prevent this functionality but on my Paper server, it works as intended.
